<?php
$this->title = "Eliminar usuario";
$this->headTitle($this->title);
?>
<div class="hero-unit">
  <h1>Eliminar usuario</h1>
  <p>Está seguro que desea eliminar el usuario 
  '<?php echo $this->escape($this->usuarios['usu_nombre'].' '.$this->usuarios['usu_apellido_1'].' '.$this->usuarios['usu_apellido_2']); ?>'?
  </p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->usuarios['usu_id_usuario']; ?>" />
  <input class="btn btn-primary btn-large" type="submit" name="del" value="Si" />
  <input class="btn btn-large" type="submit" name="del" value="No" />
</div>
</form>
</div>