<form id="formadd" method="post">
<div class="container well">
  <!-- * * * * * * *BARRA SUPERIOR * * * * * * *   -->
  <div class="row">
    <div class="span6">
      <b>Local:
      <?php echo $this->form->loc_nombre->getValue(); ?>
      </b>&nbsp;
      <input placeholder="Boleta nro." type="text">
    </div>
    <div class="span4 offset2">
      <h4><b><div id="top_total_final"></div></b></h4>
    </div>
  </div>
<div class="tabbable">
  <!-- * * * * * * * PESTAÑAS DE LOS TABS * * * * * -->
  <ul class="nav nav-tabs">
    <li class="active" id="htab1"> <a href="#tab1" data-toggle="tab">Agregar Inventario</a></li>
    <li id="htab2">                <a href="#tab2" data-toggle="tab">Datos de Venta</a></li>
    <li id="htab3">                <a href="#tab3" data-toggle="tab">Finalizar Venta</a></li>
  </ul>
  <div class="tab-content">
    
  <!-- * * * * * * * AGREGAR INVENTARIO ( TAB 1 ) * -->
    <div class="tab-pane active" id="tab1">
      <div class="well btn-danger">
        <table>
          <tr>
            <td><b>Asignar Vendedor:</b></td>
          </tr>
          <tr>
            <td><b>&nbsp;</b></td>
          </tr>
          <tr>
            <td>
              <?php echo $this->form->usu_id_usuario; ?>
            </td>
          </tr>
        </table>
      </div>
      <div class="well btn-warning">
        <div class="row">
          <div class="span6">
          <table class="table">
              <tr>
                <th class="span2">Código</th>
                <th class="span2">Cantidad</th>
                <th class="span2">Talla</th>
              </tr>
              <tr>
                <td>
                  <div class="input-append">
                  <?php echo $this->form->mer_codigo; ?>
                  <?php echo $this->form->btn_mer_codigo; ?>
                  </div>
                </td>
                <td>
                  <?php echo $this->form->f_num_mercaderia; ?>
                </td>
                <td>
                  <select id="mer_id_mercaderia" onchange="getDataPrecio()" tabindex="4" class="input-mini jumper">
                  </select>
                </td>
              </tr>
              <tr>
                <th>Artículo</th>
                <th>Color</th>
                <th>Precio</th>
              </tr>
              <tr>
                <td><?php echo $this->form->mer_articulo; ?></td>
                <td><?php echo $this->form->col_nombre; ?></td>
                <td><?php echo $this->form->hme_precio; ?></td>
              </tr>
              <tr>
                <td>
                  <b>Total Precio: </b><?php echo $this->form->f_total_mercaderia; ?>
                </td>
                <td colspan="2"><br />
                  <button name="botonGuardar" id="botonGuardar" type="button" class="btn btn-info jumper" onclick="guardarString()" tabindex="5">Agregar</button>
                  <button name="botonLimpiar" id="botonLimpiar" type="button" class="btn" onclick ="limpiarString()">Limpiar</button>
                </td>
              </tr>
          </table>
        </div>
          <div class="span5">
          <td rowspan="5" class="span4">
            <?php echo $this->form->mer_foto; ?>
            <img id="mer_foto_mini" src="" class="img-rounded" height="200px" width="200px" float="left" />
          </td>
          </div>
        </div>
      </div>
    </div>
  <!-- * * * * * * * DATOS DE LA VENTA ( TAB 2 ) *  -->
    <div class="tab-pane" id="tab2">
      <div class="row">
        <div class="span6">
          <div class="well btn-info">
            <p>
              <span><b>Forma de pago del cliente:</b></span>
            </p>
            <table>
              <thead>
                <tr>
                  <th>Forma de Pago</th>
                  <th>Monto</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <?php echo $this->form->tip_id_tipo_pago; ?>
                  </td>
                  <td>
                    <?php echo $this->form->f_pago_monto; ?>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="well">
            <p>
              <span><b>Otro:</b></span>
            </p>
            <table>
              <thead>
                <tr>
                  <th>Tipo</th>
                  <th><span class="pull-left">Porcentaje (%)</span></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                  <?php echo $this->form->des_id_descuento; ?>
                  </td>
                  <td>
                  <?php echo $this->form->f_descuento_monto; ?>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="span6">
          <div class="well btn-success">
            <p>
              <span><b>Extras de pago:</b></span>
            </p>
            <table>
              <thead>
                <tr>
                  <th>Extra</th>
                  <th>Valor</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Código Validación Cheque:</td>
                  <td><?php echo $this->form->tphv_codigo_cheque; ?></td>

                </tr>
                <tr>
                  <td>Nro. Cuotas:</td>
                  <td><?php echo $this->form->tphv_cant_cuotas; ?></td>

                </tr>
                <tr>
                  <td>Cuota Aprox.:</td>
                  <td><?php echo $this->form->f_monto_cuota; ?></td>

                </tr>
                <tr>
                  <td>Datos del Vale:</td>
                  <td><?php echo $this->form->tphv_observacion_smo; ?></td>

                </tr>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>
  
  <!-- * * * * * * * RESUMEN DE VENTA ( TAB 3 )* *  -->
    <div class="tab-pane" id="tab3">
      <div class="row">
        <div class="span6">
          <p>
            <span><b>Venta:</b></span>
            <span class="pull-right"><button class="btn btn-mini" href="#tab1" data-toggle="tab">Agregar <img class="icon-plus"></button></span>
          </p>
          <div>
            <ul class="thumbnails">
              <li class="span2">
                <div class="thumbnail">
                  <img src="https://s3.amazonaws.com/jetstrap-site/images/what_icon.png">
                  <h5>codigo</h5>
                  <p>cantidad + precio</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
        <div class="span6">
          <div class="well">
            <b>Productos:</b>
            <ul>
              <li>codigo, talla, color, cantidad, precio</li>
              <li>codigo, talla, color, cantidad, precio</li>
              <li>codigo, talla, color, cantidad, precio</li>
              <li><b>Total: $129.800</b></li>
            </ul>
            <b>Resumen:</b>
            <ul>
              <li>Vendedor: Xasdasd Ysadasdasds</li>
              <li>Forma Pago: Credito, $129000 , Efectivo: $800 </li>
              <li>Descuento: $2000</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <!-- * * * * * * * * * * FIN TABS  * * * * * * *  -->
  </div>
</div>

  <!-- * * * * * * * TABLA DE LA VENTA (INV)* * * * -->
    <div class="row">
    <div class="span6">
      <table id="stringMercanciaTable" class="table table-bordered table-condensed">
      <thead><th>Código</th><th>Cantidad</th><th>Talla</th><th>Precio</th></thead>
      <tbody></tbody>
      </table>
    </div>
  <!-- * * * * * *  VALORES TOTALES DE LA VENTA * * -->
    <div class="span6">
      <table class="table pull-right">
        <tbody>
          <tr>
            <td>Total:</td><td><?php echo $this->form->f_total; ?></td>
          </tr>
          <tr>
            <td>Dcto:</td><td><?php echo $this->form->f_dcto; ?></td>
          </tr>
          <tr>
            <td>Vuelto:</td><td><?php echo $this->form->f_vuelto; ?></td>
          </tr>
          <tr>
            <td>Total Final:</td><td><?php echo $this->form->f_total_final; ?></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- * * * * * * * BOTONERA BOTTOM '<' '>' 'OK'* -->
  <ul class="pager">
    <li><a href="#tab1" data-toggle="tab" class="btn-danger">[X]</a></li>
    <li><a href="#tab1" data-toggle="tab">&lt;&lt;</a></li>
    <li><a href="#tab2" data-toggle="tab" class="btn-success">&gt;&gt;</a></li>
    <li><?php echo $this->form->submit; ?></li>
  </ul>
<?php echo $this->form->loc_nombre; ?>
<?php echo $this->form->stringMercanciaInput; ?>
<?php echo $this->form->tipoSubmit; ?>
<?php echo $this->form->returnUrl; ?>
</div>
</form>
  <!-- * * * * * * * FUNCIONES JAVA SCRIPT * * * * -->
<script>
function calcularVuelto(){
  if( $('#f_total_final').val() == "" )     $('#f_total_final').val('0');
  
  var f_total_final = parseInt( $('#f_total_final').val() );
  var f_pago_monto = parseInt( $('#f_pago_monto').val() );
  if($('#tip_id_tipo_pago option:selected').text() == "Efectivo"){
    $('#f_vuelto').val( f_pago_monto - f_total_final );
  }
  else{
    $('#f_vuelto').val( "0" );
  }
}

function calcularPago(){
  if( $('#f_total_final').val() == "" )     $('#f_total_final').val('0');
  if( $('#f_pago_monto').val() == "" )      $('#f_pago_monto').val('0');
  
  var f_total_final = parseInt( $('#f_total_final').val() );
  
  $('#f_pago_monto').val( f_total_final );
}

function calcularDescuento(){
  if( $('#f_total').val() == "" )                $('#f_total').val('0');
  if( $('#f_dcto').val() == "" )                $('#f_dcto').val('0');
  if( $('#f_descuento_monto').val() == "" )     $('#f_descuento_monto').val('0');

  var str = $('#des_id_descuento option:selected').text();
  str = str.split("(");
  var str2 = str[1].split("%");

  var f_total = parseInt( $('#f_total').val() );
  var f_descuento_monto =   parseInt ( f_total * ( parseInt( str2[0] )/100 ) );

  $('#f_dcto').val( f_descuento_monto );
  $('#f_descuento_monto').val( f_descuento_monto );
  calcularValoresTotales();
}

function guardarString(){
  if($('#mer_codigo').val() != null && $('#mer_codigo').val() != ""){
    var inicioStrInput = $('#stringMercanciaInput').val();

    if( inicioStrInput != ""){
      inicioStrInput +='-';
    }
    var inventarioStr=
      '<td>'+$('#mer_codigo').val()+'</td><td>'+$('#f_num_mercaderia').val()+'</td>';
    var inventarioStrInput= 
      '|'+$('#mer_codigo').val()+'|'+$('#f_num_mercaderia').val()+'|';

    inventarioStr+= '<td>'+$('#mer_id_mercaderia option:selected').text() +'</td>';
    inventarioStrInput+= $('#mer_id_mercaderia option:selected').text() +'|';

    inventarioStr+= '<td>'+$('#f_total_mercaderia').val() +'</td>';
    inventarioStrInput+= $('#f_total_mercaderia').val() +'|';

    $('#stringMercanciaTable').find('tbody:last').append("<tr>"+inventarioStr+"</tr>");
    $('#stringMercanciaInput').val( inicioStrInput + inventarioStrInput );

    agregarValorMercaderia();
  }
}

function limpiarString(){
  //$('#stringMercancia').html("");
  $("#stringMercanciaTable tbody tr").remove();
  $('#stringMercanciaInput').val("");
  $('#f_total').val('0');
  $('#f_dcto').val('0');
  $('#f_vuelto').val('0');
  $('#f_total_final').val('0');
}

function agregarValorMercaderia() {
  if( $('#f_total').val() == "" )           $('#f_total').val('0');
  if( $('#f_dcto').val() == "" )            $('#f_dcto').val('0');
  if( $('#f_vuelto').val() == "" )          $('#f_vuelto').val('0');
  if( $('#f_total_final').val() == "" )     $('#f_total_final').val('0');
  
  var f_total_mercaderia =      parseInt( $('#f_total_mercaderia').val() );
  var f_total =  parseInt( f_total_mercaderia + parseInt($('#f_total').val()) );
  
  $('#f_total').val( f_total );
  calcularValoresTotales();
}

function calcularValoresTotales() {
  if( $('#f_total').val() == "" )           $('#f_total').val('0');
  if( $('#f_dcto').val() == "" )            $('#f_dcto').val('0');
  if( $('#f_vuelto').val() == "" )          $('#f_vuelto').val('0');
  if( $('#f_total_final').val() == "" )     $('#f_total_final').val('0');
  
  var f_total =  parseInt($('#f_total').val());
  var f_total_final =     parseInt( f_total - parseInt($('#f_dcto').val()) );
  
  $('#f_total_final').val( f_total_final );
  $('#top_total_final').text('TOTAL: $'+ f_total_final );
}

function calcularTotalMonto(){
  if( $('#f_num_mercaderia').val() == "" )          $('#f_num_mercaderia').val('0');
  if( $('#hme_precio').val() == "" )                $('#hme_precio').val('0');
  if( $('#f_total_mercaderia').val() == "" )        $('#f_total_mercaderia').val('0');
  
  var cantidad = parseInt( $('#f_num_mercaderia').val() );
  var precio = parseInt(  $('#hme_precio').val() );
  var resultado = parseInt(cantidad * precio);
  $('#f_total_mercaderia').val(resultado);
}

window.onload=function(){
calcularTotalMonto();
};
  
function getDataMercaderia(){
  var valor = $('#mer_codigo').val();
  if( valor != null && valor != "" ){
    var mercaderia = parseInt( valor );
    if( mercaderia > 0){
      $.post('/venta/ajaxfrombd', {mercaderia: mercaderia}, function (response){
        var record = response;
        $('#mer_articulo').val(record[0].mer_articulo);
        $('#col_nombre').val(record[0].col_nombre);
        $('#mer_foto').val(record[0].mer_foto);
        $('#mer_foto_mini').attr('src', "/img/mercaderia/" + record[0].mer_foto);
        $('#hme_precio').val(record[0].hme_precio);
        var i = 0;            //TALLAS
        $('#mer_id_mercaderia').empty();
        for(i=0; i<record.length ; i++){
          $('#mer_id_mercaderia').append($('<option>', { value : record[i].mer_id_mercaderia }).text(record[i].tal_talla));
          getDataPrecio();
        }
      }, 'json');
    } else {
        alert('Por favor pon un número mayor a 0.');
    }
  }else{
    $('#mer_articulo').val("");
    $('#col_nombre').val("");
    $('#mer_foto').val("");
    $('#hme_precio').val("");
    $('#mer_id_mercaderia').empty();
  }
}

function getDataPrecio(){
  var valor = $('#mer_id_mercaderia').val();
  if( valor != null && valor != "" ){
    var id_mercaderia = parseInt( valor );
    if( id_mercaderia > 0){
      $.post('/venta/ajaxfrombd', {id_mercaderia: id_mercaderia}, function (response){
        var record = response;
        $('#hme_precio').val(record[0].hme_precio);
        var cantidad = parseInt( $('#f_num_mercaderia').val() );
        var resultado = parseInt(cantidad * record[0].hme_precio);
        $('#f_total_mercaderia').val(resultado);
      }, 'json');
    }else{
      $('#hme_precio').val('0');
       // alert('Por favor pon un número mayor a 0.');
    }
  }else{
    $('#hme_precio').val('0');
  }
  calcularTotalMonto();
}

$("document").ready(function(){             //RECORRER LOS CAMPOS CON TAB
  $('[class*="jumper"]').keypress(function(event){
    if(event.which == 43){                  //AL HACER CLIC EN EL SIGNO 'MAS' (+)
//    if(event.which == 13){                  //AL HACER CLIC EN EL SIGNO ENTER
    cb = parseInt($(this).attr('tabindex'));
      if(cb == 5) cb = 0;
      if ( $(":input[tabindex='" + (cb + 1) + "']") != null) {
        $(":input[tabindex='" + (cb + 1) + "']").focus();
        $(":input[tabindex='" + (cb + 1) + "']").select();
        //alert(cb);
        return false;
      }
    }
  });
});

$(document).ready(function() {               // ELIMINAR ENTER PARA ENVIAR FORM
    $("input:not(button)").keypress(function(e) {
        if (e.which == 13 ) {
            e.preventDefault();
            return false;
        }
    });
});
</script>