<?php include('menuencbod.phtml'); ?>
<div class="container well">
  <h1>Perfil Encargado de Bodega</h1>
  <div class="row-fluid pull-left">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/encbod/inventariobodega">
      <h1>Inventario de Bodega</h1>
      <p>Se puede visualizar el inventario de las bodegas, así como el detalle de cada una.</p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/encbod/transacciones">
      <h1>Transacciones</h1>
      <p>Este proceso permite generar las transacciones de inventario desde y hacia las bodegas.</p>
    </a>
  </div>
  <span>&nbsp;</span>
  <div class="row-fluid pull-right">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/encbod/mantenedormercaderia">
      <h1>Mantenedor de Mercadería</h1>
      <p>Este proceso permite al encargado de la bodega principal agregar nuevos tipos de mercadería, así como modificarla o eliminarla. </p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/encbod/listafallas">
      <h1>Fallas y Devoluciones</h1>
      <p>Se puede consultar la lista de fallas y/o devoluciones realizadas por parte de los clientes. También se puede agregar nuevos estados a éstas. </p>
    </a>
  </div>
</div>