<?php include('menuencbod.phtml'); ?>
<div class="container well">
  <h1>Perfil Encargado de Bodega</h1>
  <div class="row-fluid pull-left">
    <div class="well span6 btn btn-primary" style="height:200px;">
      <h1>Inventario de Bodega</h1>
      <p>Se puede visualizar el inventario de las bodegas, así como el detalle de cada una.</p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/encbod/inventariobodega">Ir</a>
      </p>
    </div>

    <div class="well span6 btn btn-primary" style="height:200px;">
      <h1>Transacciones</h1>
      <p>Este proceso permite generar las transacciones de inventario desde y hacia las bodegas.</p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/encbod/transacciones">Ir</a>
      </p>
    </div>
  </div>
  <div class="row-fluid pull-right">
    <div class="well span6 btn btn-primary" style="height:200px;">
      <h1>Mantenedor de Mercadería</h1>
      <p>Este proceso permite al encargado de la bodega principal agregar nuevos tipos de mercadería, así como modificarla o eliminarla. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/encbod/mantenedormercaderia">Ir</a>
      </p>
    </div>

    <div class="well span6" style="height:200px;">
      <h1>Fallas y Devoluciones</h1>
      <p>Se puede consultar la lista de fallas y/o devoluciones realizadas por parte de los clientes. También se puede agregar nuevos estados a éstas. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/encbod/listafallas">Ir</a>
      </p>
    </div>
  </div>
</div>