<?php include('menucajero.phtml'); ?>
<div class="container well">
<h3>
  Cambios y/o Anulaciones
</h3>
  <div>
    <?php echo $this->action('index', 'venta'); ?>
  </div>
</div>
<script>
$( "#textinput7" ).datepicker({
  "format": "dd/mm/yyyy",
  "weekStart": 1,
  "autoclose": true});
$( "#textinput8" ).datepicker({
  "format": "dd/mm/yyyy",
  "weekStart": 1,
  "autoclose": true});
recorrerLiPrincipal('cambiosanulaciones');
</script>