<?php include('menucajero.phtml'); ?>
<div class="container well">
  <h1>Perfil Cajero</h1>
  <div class="row-fluid">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/cajero/ventas">
      <h1>Ventas</h1>
      <p>Este proceso permite ingresar una nueva venta para el local.</p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/cajero/cierrecaja">
      <h1>Cierre de Caja</h1>
      <p>Este proceso permite realizar Entregas de venta y Cierres de caja. </p>
    </a>
  </div>
  <span>&nbsp;</span>
  <div class="row-fluid">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/cajero/inventario">
       <h1>Inventario</h1>
       <p>Este proceso muestra la lista de inventario disponible en la bodega del local.</p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/cajero/cambiosanulaciones">
      <h1>Cambios y/o Anulaciones</h1>
      <p>Este proceso se ocupa al recibir una boleta de parte de un cliente, para un cambio y/o reparación de una mercadería. </p>
    </a>
  </div>
  <span>&nbsp;</span>
  <div class="row-fluid">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/cajero/abonos">
     <h1>Abonos</h1>
     <p>Esta pestaña muestra la lista de abonos por cliente, y permite ingresar un abono a un cliente nuevo.</p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/cajero/credito">
      <h1>Crédito de SMO</h1>
      <p>Permite ver la lista de clientes con crédito de SMO y sus estados de cuenta. </p>
    </a>
  </div>
</div>