<?php include('menucajero.phtml'); ?>
<div class="container well">
  <h1>Perfil Cajero</h1>
  <div class="row-fluid">
  <div class="span6">
    
    <div class="well btn btn-danger" style="height:200px;">
      <h1>Ventas</h1>
      <p>Este proceso muestra la lista de transacciones del sistema, realizando búsquedas para filtrar sus resultados y revisar en detalle una transacción.</p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/cajero/ventas">Ir</a>
      </p>
    </div>

    <div class="well" style="height:200px;">
      <h1>Inventario</h1>
      <p>Este proceso muestra la lista de cierres de caja realizadas en el sistema, con la posibilidad de revisarlas en detalle.<br><br></p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/cajero/inventario">Ir</a>
      </p>
    </div>
    
    <div class="well" style="height:200px;">
      <h1>Abonos</h1>
      <p>Este proceso muestra la lista de cierres de caja realizadas en el sistema, con la posibilidad de revisarlas en detalle.<br><br></p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/cajero/abonos">Ir</a>
      </p>
    </div>
    
  </div>
  <div class="span6">
    
    <div class="well" style="height:200px;">
      <h1>Cierre de Caja</h1>
      <p>Esta opción permite al Administrador, crear, modificar y eliminar los datos de las entidades clave del sistema. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/cajero/cierrecaja">Ir</a>
      </p>
    </div>

    <div class="well" style="height:200px;">
      <h1>Cambios y/o Anulaciones</h1>
      <p>Acceso directo a la base de datos del sistema. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/cajero/cambiosanulaciones">Ir</a>
      </p>
    </div>
    
    <div class="well" style="height:200px;">
      <h1>Crédito de SMO</h1>
      <p>Acceso directo a la base de datos del sistema. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/cajero/credito">Ir</a>
      </p>
    </div>
    
  </div>
  </div>
</div>