<?php include('menuuser.phtml'); ?>
<div class="container">

<div class="row-fluid span12">
  <div class="span3">
    <div class="well well-large pull-left" style="overflow:auto;height:600px;">
      <h4>Mensajes:</h4>

<?php   foreach($this->mensaje as $msg) {       //HORA Y MENSAJES
          $time = DateTime::createFromFormat('Y-m-d H:i:s', $msg['men_fecha'] )->format('H:i:s, d/m/Y');
          echo "<p><b>".$time."</b></p>";
          echo "<p>".$msg['men_mensaje']."</p>";
        }
?>
    </div>
  </div>
  <div class="span9">
    <h3>Seleccione Perfil:</h3>
<?php    //BOTONES DE PERFILES SEGUN USUARIO
      foreach($this->usuariohasperfiles as $per){
        echo '<a class="btn btn-large btn-block"  href="/'.$per->per_nombre_dir.'">';
        echo '<h3>'.$per->per_nombre.'</h3>';
        echo '</a>';
      } 
?>
  </div>
</div>
  </div>