<?php include('menuencloc.phtml'); ?>
<div class="container well">
  <h1>Perfil Encargado de Bodega</h1>
  <div class="row-fluid pull-left">
    <div class="well span6 btn btn-warning" style="height:200px;">
      <h1>Inventario de Bodega</h1>
      <p>Se puede visualizar el inventario de la bodega, así como el detalle de cada mercadería.</p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/encloc/inventariobodega">Ir</a>
      </p>
    </div>

    <div class="well span6 btn btn-warning" style="height:200px;">
      <h1>Transacciones</h1>
      <p>Este proceso permite aceptar y revisar las transacciones de inventario.</p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/encloc/transacciones">Ir</a>
      </p>
    </div>
  </div>
</div>