<?php include('menuencloc.phtml'); ?>
<div class="container well">
  <h1>Perfil Encargado de Bodega</h1>
  <div class="row-fluid">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/encloc/inventariobodega">
      <h1>Inventario de Bodega</h1>
      <p>Se puede visualizar el inventario de la bodega, así como el detalle de cada mercadería.</p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/encloc/transacciones">
      <h1>Transacciones</h1>
      <p>Este proceso permite aceptar y revisar las transacciones de inventario.</p>
    </a>
  </div>
</div>