<?php include('menuencloc.phtml'); ?>
<div class="container well">
<h3>
  Inventario de bodega
</h3>
    <!--
<form>
  <div class="row-fluid">

    <div class="span4">
      <div class="control-group">
        <label for="textinput1">
          Código:
        </label>
        <input name="textinput1" class="search-query" type="search">
      </div>
      <div class="control-group">
        <label for="textinput7">
          Fecha Inicial:
        </label>
        <input name="textinput7" id="textinput7" type="">
      </div>
      <div class="control-group">
        <label for="textinput8">
          Fecha Final:
        </label>
        <input name="textinput8" id="textinput8" type="">
      </div>
    </div>
    <div class="span4">
      <div class="control-group">
        <label for="selectinput5">
          Origen:
        </label>
        <select name="selectinput5">
        </select>
      </div>
      <div class="control-group">
        <label for="selectinput6">
          Destinatario:
        </label>
        <select name="selectinput6">
        </select>
      </div>
    </div>
    <div class="span4">
      <a class="btn btn-primary disabled" href="#">
        Filtrar
      </a>
    </div>
  </div>
</form>
  -->
  <div>
    <?php echo $this->action('indexlocal', 'inventario'); ?>
  </div>
</div>
<script>
$( "#textinput7" ).datepicker({
  "format": "dd/mm/yyyy",
  "weekStart": 1,
  "autoclose": true});
$( "#textinput8" ).datepicker({
  "format": "dd/mm/yyyy",
  "weekStart": 1,
  "autoclose": true});
recorrerLiPrincipal('inventariobodega');
</script>