<?php
$this->title = "Eliminar Cliente";
$this->headTitle($this->title);
?>
<div class="hero-unit">
  <p>Eliminar cliente: '
<?php echo $this->data['cli_nombre'].' '.$this->data['cli_apellido_1'].' '.$this->data['cli_apellido_2'];   ?>'?
  </p>
  <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
  <div>
    <input type="hidden" id="id_cliente" name="id_cliente" value="<?php echo $this->id_cliente_get; ?>" />
    <input class="btn btn-primary btn-large" type="submit" name="eliminar" value="Eliminar" />
    &nbsp;
    <input class="btn btn-danger btn-large" type="submit" onclick="document.close()" name="eliminar" value="Cancelar" />
  </div>
  </form>
</div>