<?php include('menuadmin.phtml'); ?>
<div class="container well">
  <h1>Perfil Administrador</h1>
  <div class="row-fluid pull-left">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/admin/transacciones">
      <h1>Transacciones</h1>
      <p>Este proceso muestra la lista de transacciones del sistema, realizando búsquedas para filtrar sus resultados y revisar en detalle una transacción.</p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/admin/cierrescaja">
      <h1>Cierres de Caja</h1>
      <p>Este proceso muestra la lista de cierres de caja realizadas en el sistema, con la posibilidad de revisarlas en detalle.<br><br></p>
    </a>
  </div>  
  <span>&nbsp;</span>
  <div class="row-fluid pull-right">
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/admin/mantenedores">
      <h1>Mantenedores</h1>
      <p>Esta opción permite al Administrador, crear, modificar y eliminar los datos de las entidades clave del sistema. </p>
    </a>
    <a class="span6 btn btn-primary btn-large" style="height:200px;" href="/admin/basedatos">
      <h1>Base de Datos</h1>
      <p>Acceso directo a la base de datos del sistema. </p>
    </a>
  </div>
</div>