<?php include('menuadmin.phtml'); ?>
<div class="container well">
  <h1>Perfil Administrador</h1>
  <div class="row-fluid pull-left">
    <div class="well span6 btn btn-primary" style="height:200px;">
      <h1>Transacciones</h1>
      <p>Este proceso muestra la lista de transacciones del sistema, realizando búsquedas para filtrar sus resultados y revisar en detalle una transacción.</p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/admin/transacciones">Ir</a>
      </p>
    </div>

    <div class="well span6" style="height:200px;">
      <h1>Cierres de Caja</h1>
      <p>Este proceso muestra la lista de cierres de caja realizadas en el sistema, con la posibilidad de revisarlas en detalle.<br><br></p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/admin/cierrescaja">Ir</a>
      </p>
    </div>
  </div>
  <div class="row-fluid pull-right">
    <div class="well span6 btn btn-primary" style="height:200px;">
      <h1>Mantenedores</h1>
      <p>Esta opción permite al Administrador, crear, modificar y eliminar los datos de las entidades clave del sistema. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/admin/mantenedores">Ir</a>
      </p>
    </div>

    <div class="well span6 btn btn-primary" style="height:200px;">
      <h1>Base de Datos</h1>
      <p>Acceso directo a la base de datos del sistema. </p>
      <p>
      <a class="btn btn-primary btn-large pull-right" href="/admin/basedatos">Ir</a>
      </p>
    </div>
  </div>
</div>