<?php include('menuadmin.phtml'); ?>
<div class="container well">
<!--
<h3>
  Transacciones
</h3>
<form>
  <div class="row">
    <div class="span4">
      <div class="control-group">
        <label for="textinput7">
          Fecha Inicial:
        </label>
        <input name="textinput7" id="textinput7" type="">
      </div>
      <div class="control-group">
        <label for="textinput8">
          Fecha Final:
        </label>
        <input name="textinput8" id="textinput8" type="">
      </div>
    </div>
    <div class="span4">
      <div class="control-group">
        <label for="selectinput5">
          Origen:
        </label>
        <input type="text" name="selectinput5" id="selectinput5" data-provide="typeahead" data-items="4">
      </div>
      <div class="control-group">
        <label for="selectinput6">
          Destinatario:
        </label>
        <input type="text" name="selectinput6" id="selectinput6" data-provide="typeahead" data-items="4">
      </div>
    </div>
    <div class="span4">
      <a class="btn btn-primary disabled" href="#">
        Filtrar
      </a>
    </div>
  </div>
</form>
-->  
  <div>
    <?php echo $this->action('index', 'transaccion'); ?>
  </div>
</div>

<script type="text/javascript">
$( "#textinput7" ).datepicker({
  "format": "dd/mm/yyyy",
  "weekStart": 1,
  "autoclose": true});

$( "#textinput8" ).datepicker({
  "format": "dd/mm/yyyy",
  "weekStart": 1,
  "autoclose": true});

var origen = <?php echo $this->origen; ?>;
$( '#selectinput5' ).typeahead( {source: origen} );
$( '#selectinput6' ).typeahead( {source: origen} );

recorrerLiPrincipal('transacciones');
</script>